language: objective-c

before_install:
  - gem install activesupport
  - gem update cocoapods
  - gem install slather

script: ./build.sh ci

# Whitelist for branches
branches:
  only:
    - master

after_success:
  - slather
