language: objective-c
osx_image: xcode7.3

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

script: ./build.sh ci

# Whitelist for branches
branches:
  only:
    - master
